
# Access to current environment DB
#
#  Default():
#    - Src:
#      <<: *TYPO3_DB
#      table: fe_users
#    - Dest: export.json

TYPO3_DB: &TYPO3_DB
  type: db
  driver: mysql
  server: {TYPO3_CONF_VARS.DB.Connections.Default.host}
  port: {TYPO3_CONF_VARS.DB.Connections.Default.port}
  username: {TYPO3_CONF_VARS.DB.Connections.Default.user}
  password: {TYPO3_CONF_VARS.DB.Connections.Default.password}
  database: {TYPO3_CONF_VARS.DB.Connections.Default.dbname}
  charset: {TYPO3_CONF_VARS.DB.Connections.Default.charset}
